FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PollsAPIBDemo1

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

    + Attributes (Example)

# Data Structures
## Example
+ example: `__main__`